version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data/

  pgadmin:
      image: dpage/pgadmin4:4
      environment:
        PGADMIN_DEFAULT_EMAIL: test
        PGADMIN_DEFAULT_PASSWORD: test
      ports:
        - 8080:80
      volumes:
        - pgadmin-data:/var/lib/pgadmin

volumes:
  data:
  pgadmin-data: